### PR TITLE
Fix to disable options that crash on AMD Navi 32 and Navi 48

### LINKED ISSUE #1001: Crash on lobby join - AMD Related?
I'm just trying out this game for the first time with some friends but I get a crash on joining or creating any lobby. Singleplayer, self hosted, other players... All the same crash just before it finishes loading or just as it starts showing the lobby.

There is no crashdump in the `steamapps/Reactive Drop` folder but I've attached windows event viewer log below.

I'd suspect this may be the same issue, though I haven't gone as far as them in troubleshooting yet: https://steamcommunity.com/app/563560/discussions/2/628941617404860002/

I've tried:
- Restarting steam
- Restarting windows
- Reinstalling GPU drivers
- Validating game files
- Reinstalling game
- Double checking theres no workshop subscriptions
- Different video settings
- Updating windows
- fastprox.dll temporary rename
- Strong language

**Output from windows event viewer:**
Faulting application name: reactivedrop.exe, version: 1.0.0.0, time stamp: 0xa3e95730
Faulting module name: AMDXN32.DLL, version: 32.0.22021.1009, time stamp: 0x68ed2af9
Exception code: 0xc0000005
Fault offset: 0x0098ad59
Faulting process id: 0x3EB8
Faulting application start time: 0x1DC54464A9A8452
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Alien Swarm Reactive Drop\reactivedrop.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\u0420422.inf_amd64_cb23ea54e356fea3\B420106\AMDXN32.DLL
Report Id: ddccdaab-133d-406c-98d5-54810575e992
Faulting package full name: 
Faulting package-relative application ID: 

**System Specs:**
Device name	Pearl
Processor	AMD Ryzen 5 8400F 6-Core Processor              (4.20 GHz)
Installed RAM	32.0 GB (31.6 GB usable)
Device ID	B5645079-4736-4243-8D12-DC536F5F8BEA
Product ID	00330-80000-00000-AA684
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Pro
Version	25H2
Installed on	‎2024-‎04-‎01
OS build	26200.7171
Experience	Windows Feature Experience Pack 1000.26100.265.0

**GPU**
GPU - AMD  Radeon RX 7800 XT - Primary/Discrete
VRAM - 16368 MB - GDDR6 2438 MHz
Graphics - AMD  Radeon RX 7800 XT
Graphics Manufacturer - Powered by AMD
Usable Memory Size - 16368 MB
Core Clock - 2254 MHz
Memory Type - GDDR6
Memory Clock - 2438 MHz
Memory Bit Rate - 19.50 Gbps
Total Memory Bandwidth - 624 GByte/s
BIOS Part Number - 113-APM6771OC-58A2
BIOS Version - 022.002.001.025
BIOS Date - 2023/11/13 23:31
Device ID - 747E
Revision ID - C8
Vendor ID - 1002
SubSystem ID - 2413
SubSystem Vendor ID - 1458
Bus Type - PCI Express 4.0
Current Bus Settings - PCI Express 4.0 x8

**GPU Driver**
GPU - AMD  Radeon RX 7800 XT - Primary/Discrete
VRAM - 16368 MB - GDDR6 2438 MHz
Driver Version - 25.20.21.01-251013a-420422C-AMD-Software-Adrenalin-Edition
AMD Windows Driver Version - 32.0.22021.1009
Direct3D API Version - 12.2
Vulkan™ API Version - 1.4.325
OpenCL™ API Version - 2.0
OpenGL® API Version - 4.6
Direct3D® Driver Version - 9.17.11.0284
Vulkan™ Driver Version - 2.0.364
OpenCL® Driver Version - 32.0.22021.1009
OpenGL® Driver Version - 32.0.22021.1009
2D Driver Version - 8.1.1.1634
2D Driver File Path - /REGISTRY/MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}/0000
UI Version - 2025.1013.1251.2083
AMD Audio Driver Version - 10.0.1.40
Driver Provider - Advanced Micro Devices, Inc.
Windows Edition - Windows 11 Professional (64 bit)
Windows Version - 25H2

### PR DESCRIPTION
**Pull request by mithrand0**
Just a quick workaround, but in the meantime, this fixes #1001

### CODE REVIEW

**Comment by mithrand0** [comment]
Waiting for a little more feedback on the exact combination

**Comment by jhh8** [comment]
if someone has r_shadows 0 then having rd_flashlightshadows 1 and/or rd_env_projectedtexture_enabled 1 wont matter, game will act like those are on 0

File: src/game/client/swarm/vgui/rd_vgui_settings_video.cpp [hunk 1]
```diff
@@ -8,13 +8,84 @@
...
+		// XXX: debug
+		//const char* driverName = "AMD Radeon RX 7900 XTX";
+		const char* driverName = info.m_pDriverName;
+
+		DevMsg("Detected GPU: %s\n", info.m_pDriverName);
+
+		// if AMD
+		if (info.m_VendorID == 0x1002) {
+			// navi 32
+			if (strstr(driverName, "7700") != null) return true;
```
Comment (BenLubar) [inline src/game/client/swarm/vgui/rd_vgui_settings_video.cpp]: should either be using `nullptr` or `NULL`; not sure what `null` is.

Comment (mithrand0) [reply src/game/client/swarm/vgui/rd_vgui_settings_video.cpp]: Code worked, it was defined in vgui.h:
#define null 0L

But I removed the null's
